[project]
name = "tzn"
version = "2026.1.0"
description = "Theoretical Fundamentals of Neural Networks"
requires-python = ">=3.11"
dependencies = [
    "datasets>=3.2.0",
    "gensim>=4.4.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "scikit-learn>=1.8.0",
    "torch-cluster>=1.6.3",
    "torch-geometric>=2.7.0",
    "torchvision>=0.25.0",
    "transformers>=4.45.0",
]

[tool.uv.extra-build-dependencies]
torch-cluster = ["torch"]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
