<script lang="ts" strictEvents>
  import PageContent from "$lib/components/PageContent.svelte";
  import PageHeader from "$lib/components/PageHeader.svelte";
  import Publication from "$lib/components/Publication.svelte";
  import type { PublicationParams } from "$lib/types/PublicationParams.ts";

  export let data: { publications: Array<PublicationParams> };
</script>

<PageHeader>
  <span slot="title">publications</span>
  <span slot="subtitle"
    >publications by categories in reversed chronological order. generated by
    jekyll-scholar.</span
  >
</PageHeader>
<PageContent>
  {#each data.publications as publication (publication.title)}
    <Publication {...publication} />
  {/each}
</PageContent>
