<script lang="ts" strictEvents>
  import PageContent from "$lib/components/PageContent.svelte";
  import PageHeader from "$lib/components/PageHeader.svelte";
  import Publication from "$lib/components/Publication.svelte";

  import type { JsonPublication } from "./JsonPublication.ts";

  export let data: { publications: Array<JsonPublication> };
</script>

<PageHeader>
  <span slot="title">publications</span>
  <span slot="subtitle"
    >publications by categories in reversed chronological order. generated by
    jekyll-scholar.</span
  >
</PageHeader>
<PageContent>
  {#each data.publications as publication (publication.title)}
    <Publication
      abstract={publication.abstract}
      authors={publication.authors}
      bib={publication.bib}
      date={new Date(publication.date)}
      pdf={publication.pdf}
      previewImage={publication.previewImage}
      tags={publication.tags}
      title={publication.title}
    />
  {/each}
</PageContent>
