name: "Deploy"
on:
  push:
    branches:
      - "master"
  workflow_dispatch:
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v3.8.1

      - name: "Cache NPM dependencies"
        uses: actions/cache@v3
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Build"
        env:
          NODE_ENV: 'production'
        run: |
          npm run build

      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "build-artifact"
          path: dist

  deploy:
    name: "Deploy the website"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Download artifact"
        uses: actions/download-artifact@v3
        with:
          name: "build-artifact"
          path: dist

      - name: "Deploy over FTP"
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.dedic.eu
          username: github-ftp-deploy@dedic.eu
          password: ${{ secrets.ftp_password }}
          protocol: ftps
          local-dir: ./dist/
          exclude: |
            .well-known/pki-validation/*
            cgi-bin/*
