name: "Deploy"
on:
  push:
    branches:
      - "master"
  workflow_dispatch:
env:
  cache-version: 1
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4.0.2

      - name: "Cache NPM dependencies"
        uses: actions/cache@v4
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Build"
        env:
          NODE_ENV: 'production'
        run: |
          npm run build

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "build-artifact"
          path: dist

  deploy:
    name: "Deploy the website"
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: "deploy"
      cancel-in-progress: true
    steps:
      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: "build-artifact"
          path: dist

      - name: "Deploy over FTP"
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.dedic.eu
          username: github-ftp-deploy@dedic.eu
          password: ${{ secrets.ftp_password }}
          protocol: ftps
          local-dir: ./dist/
          exclude: |
            .well-known/pki-validation/*
            cgi-bin/*
